"""initial schema

Revision ID: 9fface4a8c7e
Revises: 
Create Date: 2026-05-19 01:13:31.679384
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9fface4a8c7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog_extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('f95_thread_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('versions_json', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('f95_thread_id', 'content_hash')
    )
    op.create_table('digest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.Integer(), nullable=False),
    sa.Column('updates_count', sa.Integer(), nullable=False),
    sa.Column('discovery_count', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('llm_cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_state',
    sa.Column('f95_thread_id', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Integer(), nullable=False),
    sa.Column('skip_until', sa.Integer(), nullable=True),
    sa.Column('interested', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('f95_thread_id')
    )
    op.create_table('discovery_suggestions',
    sa.Column('f95_thread_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('posted_at', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.Integer(), nullable=False),
    sa.Column('last_seen_in_digest_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('f95_thread_id')
    )
    op.create_table('library_games',
    sa.Column('f95_thread_id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(), nullable=False),
    sa.Column('save_dir_name', sa.String(), nullable=True),
    sa.Column('last_played_at', sa.Integer(), nullable=True),
    sa.Column('first_played_at', sa.Integer(), nullable=True),
    sa.Column('save_count', sa.Integer(), nullable=True),
    sa.Column('total_save_size_bytes', sa.Integer(), nullable=True),
    sa.Column('install_path', sa.String(), nullable=True),
    sa.Column('installed_version', sa.String(), nullable=True),
    sa.Column('disk_size_bytes', sa.Integer(), nullable=True),
    sa.Column('latest_upstream_version', sa.String(), nullable=True),
    sa.Column('upstream_last_updated_at', sa.Integer(), nullable=True),
    sa.Column('upstream_thread_url', sa.String(), nullable=True),
    sa.Column('raw_changelog', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=False),
    sa.Column('interested', sa.Integer(), nullable=False),
    sa.Column('acknowledged_version', sa.String(), nullable=True),
    sa.Column('last_seen_in_digest_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('f95_thread_id')
    )
    op.create_table('pairings',
    sa.Column('f95_thread_id', sa.Integer(), nullable=False),
    sa.Column('save_dir_name', sa.String(), nullable=True),
    sa.Column('folder_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('paired_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('f95_thread_id')
    )
    op.create_table('digest_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('discord_message_id', sa.String(), nullable=False),
    sa.Column('embed_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('f95_thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['digest_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_message_id', 'embed_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_entries')
    op.drop_table('pairings')
    op.drop_table('library_games')
    op.drop_table('discovery_suggestions')
    op.drop_table('discovery_state')
    op.drop_table('digest_runs')
    op.drop_table('changelog_extractions')
    # ### end Alembic commands ###
